<a href="https://colab.research.google.com/github/SandKrish/Data-Cleaning/blob/main/DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving DataScience_Youtube_Videos.csv to DataScience_Youtube_Videos (1).csv
User uploaded file "DataScience_Youtube_Videos.csv" with length 62030 bytes

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("DataScience_Youtube_Videos.csv")

In [4]:
df.head(2)

,Video_Title,Video_Link,Channel_Name,Channel_Link,Total_Views,Publish_Date,Description
0,\n \n Data Science In 5 ...,https://www.youtube.com/watch?v=X3paOmcrTjQ,Simplilearn,https://www.youtube.com/c/SimplilearnOfficial,2.9M views,3 years ago,Boost your career with Simplilearn's 6-months ...
1,\n \n What REALLY is Dat...,https://www.youtube.com/watch?v=xC-c7E5PK0Y,Joma Tech,https://www.youtube.com/c/JomaOppa,3.1M views,4 years ago,Interested in Data Science? Start with learnin...

In [5]:
df.shape

(173, 7)

In [6]:
df[df.duplicated()]

,Video_Title,Video_Link,Channel_Name,Channel_Link,Total_Views,Publish_Date,Description
65,\n \n Reality behind dat...,https://www.youtube.com/shorts/R6u5EBWAssY,codebasics,https://www.youtube.com/c/codebasics,552K views,7 months ago,Reality behind data science jobs. Is machine l...
67,\n \n Coursera has an OF...,https://www.youtube.com/watch?v=y4yYTqjQHjM,Greg Hogg,https://www.youtube.com/c/GregHogg,8.5K views,3 months ago,The Pathway: Entry-Level Data Analyst ********...

In [7]:
df[df.duplicated(subset="Channel_Name")]

,Video_Title,Video_Link,Channel_Name,Channel_Link,Total_Views,Publish_Date,Description
11,\n \n How I Would Learn ...,https://www.youtube.com/watch?v=Rt6eb9VOFII,Recall by Dataiku,https://www.youtube.com/c/RecallbyDataiku,157K views,7 months ago,"In this video, I go through how I would learn ..."
12,\n \n 🔥Data Science Full...,https://www.youtube.com/watch?v=xvEKQefqQ7A,Simplilearn,https://www.youtube.com/c/SimplilearnOfficial,292K views,Streamed 8 months ago,Boost your career with Simplilearn's 6-months ...
14,\n \n 👩🏻‍💻 How to learn ...,https://www.youtube.com/watch?v=lpSw_RAPmgc,Thu Vu data analytics,https://www.youtube.com/c/Thuvu5,34K views,4 months ago,"Hey data nerds , in today's video we'll be tal..."
15,\n \n Data Scientist vs ...,https://www.youtube.com/watch?v=XW0YptcgZSk,Recall by Dataiku,https://www.youtube.com/c/RecallbyDataiku,135K views,4 months ago,Twitter: https://twitter.com/dataiku Instagram...
20,\n \n Should you become ...,https://www.youtube.com/watch?v=kr59DGtWDTs,Sundas Khalid,https://www.youtube.com/c/SundasKhalid,21K views,3 months ago,Is data analyst a pre-requisite to become a da...
...,...,...,...,...,...,...,...
161,\n \n 6 Certifications I...,https://www.youtube.com/watch?v=Q6GfF8fB7E4,Krish Naik,https://www.youtube.com/user/krishnaik06,401K views,1 year ago,Kite is a free AI-powered coding assistant tha...
164,\n \n How to get a data ...,https://www.youtube.com/watch?v=71RVNeseKZw,Tina Huang,https://www.youtube.com/c/TinaHuang1,55K views,1 year ago,This video is for those of you who are learnin...
165,\n \n What Data Scientis...,https://www.youtube.com/watch?v=sdbcHsl_crU,Recall by Dataiku,https://www.youtube.com/c/RecallbyDataiku,3.7K views,3 weeks ago,"In this video, I talk about what data scientis..."
166,\n \n 4 CR+ SALARY for D...,https://www.youtube.com/watch?v=6Gd9i3DxhkM,E-Learning Bridge,https://www.youtube.com/c/LearningBridge,343K views,1 month ago,"With 13 years of expertise, the lead instructo..."
172,\n \n Step by step roadm...,https://www.youtube.com/watch?v=H4YcqULY1-Q,codebasics,https://www.youtube.com/c/codebasics,636K views,1 year ago,Complete data science roadmap: Do you want to ...

In [8]:
result_df = df.drop_duplicates(keep='first')

In [9]:
result_df.shape

(171, 7)

In [10]:
df[df.duplicated()]

,Video_Title,Video_Link,Channel_Name,Channel_Link,Total_Views,Publish_Date,Description
65,\n \n Reality behind dat...,https://www.youtube.com/shorts/R6u5EBWAssY,codebasics,https://www.youtube.com/c/codebasics,552K views,7 months ago,Reality behind data science jobs. Is machine l...
67,\n \n Coursera has an OF...,https://www.youtube.com/watch?v=y4yYTqjQHjM,Greg Hogg,https://www.youtube.com/c/GregHogg,8.5K views,3 months ago,The Pathway: Entry-Level Data Analyst ********...

In [11]:
df[df['Video_Link']=='https://www.youtube.com/shorts/R6u5EBWAssY']

,Video_Title,Video_Link,Channel_Name,Channel_Link,Total_Views,Publish_Date,Description
18,\n \n Reality behind dat...,https://www.youtube.com/shorts/R6u5EBWAssY,codebasics,https://www.youtube.com/c/codebasics,552K views,7 months ago,Reality behind data science jobs. Is machine l...
65,\n \n Reality behind dat...,https://www.youtube.com/shorts/R6u5EBWAssY,codebasics,https://www.youtube.com/c/codebasics,552K views,7 months ago,Reality behind data science jobs. Is machine l...

In [12]:
result_df[result_df['Video_Link']=='https://www.youtube.com/shorts/R6u5EBWAssY']

,Video_Title,Video_Link,Channel_Name,Channel_Link,Total_Views,Publish_Date,Description
18,\n \n Reality behind dat...,https://www.youtube.com/shorts/R6u5EBWAssY,codebasics,https://www.youtube.com/c/codebasics,552K views,7 months ago,Reality behind data science jobs. Is machine l...

In [13]:
result_df[result_df['Video_Title'].str.contains('\n')]

,Video_Title,Video_Link,Channel_Name,Channel_Link,Total_Views,Publish_Date,Description
0,\n \n Data Science In 5 ...,https://www.youtube.com/watch?v=X3paOmcrTjQ,Simplilearn,https://www.youtube.com/c/SimplilearnOfficial,2.9M views,3 years ago,Boost your career with Simplilearn's 6-months ...
1,\n \n What REALLY is Dat...,https://www.youtube.com/watch?v=xC-c7E5PK0Y,Joma Tech,https://www.youtube.com/c/JomaOppa,3.1M views,4 years ago,Interested in Data Science? Start with learnin...
2,\n \n What is Data Scien...,https://www.youtube.com/watch?v=RBSUwFGa6Fk,IBM Technology,https://www.youtube.com/c/IBMTechnology,28K views,3 months ago,Data Science is the convergence of computer sc...
3,\n \n These 6 Data Jobs ...,https://www.youtube.com/watch?v=EZ66rpf_Ihg,SCALER,https://www.youtube.com/c/SCALER,"Premieres 10/1/22, 7:00 PM",NaN,NaN
4,\n \n Top Courses to Lea...,https://www.youtube.com/watch?v=ho9vNL4MYZ8,Thu Vu data analytics,https://www.youtube.com/c/Thuvu5,7.7K views,2 days ago,Hi data nerds! Today I'm sharing with you my r...
...,...,...,...,...,...,...,...
168,\n \n Let's know about D...,https://www.youtube.com/watch?v=EbB5LgG8p5M,TOUIL TALKS,https://www.youtube.com/c/OussamaTOUIL,8.8K views,Streamed 1 year ago,Let's know about Data Science - لنتعرف على علو...
169,\n \n A Complete Guide T...,https://www.youtube.com/watch?v=9ndQovLzXVQ,Rahul M,https://www.youtube.com/c/RahulMyoutubeChannel,624K views,6 months ago,Registration Link - https://relvl.co/hla4 Job ...
170,\n \n Data Science Cours...,https://www.youtube.com/watch?v=9ES-C_8TxaM,Educational Words Touch,https://www.youtube.com/c/EducationalWordsTouch,12K views,8 months ago,"Hi, Welcome to my You Tube channel Educational..."
171,\n \n 马大其实不难进？Universiti...,https://www.youtube.com/watch?v=L3mF83fzVcc,Xu Hao 旭浩,https://www.youtube.com/c/XuHaoTeoh,4.4K views,7 months ago,数据科学，Data Science是什么？ 想读硕士研究生的你，应该读Master of D...
172,\n \n Step by step roadm...,https://www.youtube.com/watch?v=H4YcqULY1-Q,codebasics,https://www.youtube.com/c/codebasics,636K views,1 year ago,Complete data science roadmap: Do you want to ...

In [14]:
result_df = result_df.copy()

In [15]:
result_df['Video_Title'] = result_df['Video_Title'].replace(r'\n',' ', regex=True) 
result_df['Video_Title'].str.strip()
result_df.head(2)

,Video_Title,Video_Link,Channel_Name,Channel_Link,Total_Views,Publish_Date,Description
0,Data Science In 5 Mi...,https://www.youtube.com/watch?v=X3paOmcrTjQ,Simplilearn,https://www.youtube.com/c/SimplilearnOfficial,2.9M views,3 years ago,Boost your career with Simplilearn's 6-months ...
1,What REALLY is Data ...,https://www.youtube.com/watch?v=xC-c7E5PK0Y,Joma Tech,https://www.youtube.com/c/JomaOppa,3.1M views,4 years ago,Interested in Data Science? Start with learnin...

In [16]:
display(result_df[result_df['Channel_Name'].str.contains('\n', na= False)])
display(result_df[result_df['Total_Views'].str.contains('\n', na = False)])
display(result_df[result_df['Publish_Date'].str.contains('\n', na = False)])
display(result_df[result_df['Description'].str.contains('\n', na = False)])

Empty DataFrame
Columns: [Video_Title, Video_Link, Channel_Name, Channel_Link, Total_Views, Publish_Date, Description]
Index: []

Empty DataFrame
Columns: [Video_Title, Video_Link, Channel_Name, Channel_Link, Total_Views, Publish_Date, Description]
Index: []

Empty DataFrame
Columns: [Video_Title, Video_Link, Channel_Name, Channel_Link, Total_Views, Publish_Date, Description]
Index: []

Empty DataFrame
Columns: [Video_Title, Video_Link, Channel_Name, Channel_Link, Total_Views, Publish_Date, Description]
Index: []